// Lap host contracts for the develop-session IPC (lap-a52 / TASK-302).
//
// The RECIPE CONTRACT section below is the generated TypeScript contract of
// rapidraw-edit-model, copied verbatim from the pinned engine revision
// e1035c38aa1150ac350faa3661f26144a922ea91 (see
// docs/raw-development/engine-lock.json, resource
// crates/rapidraw-edit-model/gen/recipe.ts,
// sha256 a15f5b4fcff133069539bb41b57028572b30d1a611157187238ad209d97749fa,
// verified against the committed bytes). Regenerate from the engine and
// re-copy; do not hand-edit the generated part.
//
// The LAP IPC CONTRACT section mirrors the Rust DTOs in
// src-tauri/src/develop/sessions.rs (serde camelCase).
// Generated by rapidraw-edit-model v0.1.0 (src/contract.rs). DO NOT EDIT.
// Regenerate with:
//   cargo test --manifest-path crates/rapidraw-edit-model/Cargo.toml -- --ignored update_generated_files
// then commit the changed files under crates/rapidraw-edit-model/gen/.
// Schema documentation: Lap repository docs/raw-development/schema.md.

export const RECIPE_SCHEMA_VERSION = 1;

export type SectionId = 'basic' | 'curves' | 'color' | 'details' | 'effects';

export const CANONICAL_SECTION_ORDER: SectionId[] = ['basic', 'curves', 'color', 'details', 'effects'];

export type ToneMapper = 'basic' | 'agx';
export type CurveMode = 'point' | 'parametric';
export type LensCorrectionMode = 'auto' | 'manual';
export type LensBlurShape = 'circle' | 'hexagon' | 'octagon' | 'ring';
export type SubMaskMode = 'additive' | 'subtractive' | 'intersect';

export interface CurvePoint { x: number; y: number; }
export interface Curves { [channel: string]: CurvePoint[]; luma: CurvePoint[]; red: CurvePoint[]; green: CurvePoint[]; blue: CurvePoint[]; }
export interface ParametricCurveSettings { darks: number; shadows: number; highlights: number; lights: number; whiteLevel: number; blackLevel: number; split1: number; split2: number; split3: number; }
export interface ParametricCurve { [channel: string]: ParametricCurveSettings; luma: ParametricCurveSettings; red: ParametricCurveSettings; green: ParametricCurveSettings; blue: ParametricCurveSettings; }
export interface HueSatLum { hue: number; saturation: number; luminance: number; }
export interface Hsl { [channel: string]: HueSatLum; reds: HueSatLum; oranges: HueSatLum; yellows: HueSatLum; greens: HueSatLum; aquas: HueSatLum; blues: HueSatLum; purples: HueSatLum; magentas: HueSatLum; }
export interface ColorGrading { [zone: string]: number | HueSatLum; balance: number; blending: number; global: HueSatLum; shadows: HueSatLum; midtones: HueSatLum; highlights: HueSatLum; }
export interface ColorCalibration { shadowsTint: number; redHue: number; redSaturation: number; greenHue: number; greenSaturation: number; blueHue: number; blueSaturation: number; }
export interface CropRect { x: number; y: number; width: number; height: number; }
export interface LensDistortionParams { k1: number; k2: number; k3: number; model: number; tca_vr: number; tca_vb: number; vig_k1: number; vig_k2: number; vig_k3: number; }
export interface SectionVisibility { [section: string]: boolean; basic: boolean; curves: boolean; color: boolean; details: boolean; effects: boolean; }
export interface MaskSectionVisibility { [section: string]: boolean; basic: boolean; curves: boolean; color: boolean; details: boolean; effects: boolean; }
export interface SubMask { id: string; name: string | null; invert: boolean; visible: boolean; opacity: number; mode: SubMaskMode; type: string; parameters: unknown; }
export interface MaskLocalAdjustments {
  exposure: number; brightness: number; contrast: number; highlights: number; shadows: number; whites: number; blacks: number;
  toneMapper: ToneMapper;
  temperature: number; tint: number; vibrance: number; saturation: number; hue: number;
  colorGrading: ColorGrading; hsl: Hsl; colorCalibration: ColorCalibration;
  clarity: number; structure: number; dehaze: number; "centré": number;
  sharpness: number; sharpnessThreshold: number; lumaNoiseReduction: number; colorNoiseReduction: number;
  chromaticAberrationRedCyan: number; chromaticAberrationBlueYellow: number;
  glowAmount: number; halationAmount: number; flareAmount: number;
  curves: Curves; pointCurves: Curves; parametricCurve: ParametricCurve; curveMode: CurveMode;
  sectionVisibility: MaskSectionVisibility;
}
export interface MaskContainer {
  id: string; name: string; invert: boolean; visible: boolean; opacity: number;
  adjustments: MaskLocalAdjustments; subMasks: SubMask[];
  unsupported: Record<string, unknown>;
}

/**
 * The semantic development recipe: persisted render data only.
 *
 * UI-only state (clipping overlay, AI patch session state, accordion
 * expansion, zoom, selected tool, hover previews) is intentionally absent.
 * Geometry uses the oriented, normalized coordinate system: origin at the
 * top-left of the image after orientationSteps clockwise quarter turns, unit
 * axes, crop components in [0, 1] with x + width <= 1 and y + height <= 1.
 */
export interface Recipe {
  exposure: number; brightness: number; contrast: number; highlights: number; shadows: number; whites: number; blacks: number;
  toneMapper: ToneMapper;
  curves: Curves; pointCurves: Curves; parametricCurve: ParametricCurve; curveMode: CurveMode;
  temperature: number; tint: number; vibrance: number; saturation: number; hue: number;
  colorGrading: ColorGrading; hsl: Hsl; colorCalibration: ColorCalibration;
  clarity: number; structure: number; dehaze: number; "centré": number;
  sharpness: number; sharpnessThreshold: number; lumaNoiseReduction: number; colorNoiseReduction: number;
  chromaticAberrationRedCyan: number; chromaticAberrationBlueYellow: number;
  glowAmount: number; halationAmount: number; flareAmount: number;
  grainAmount: number; grainSize: number; grainRoughness: number;
  vignetteAmount: number; vignetteMidpoint: number; vignetteRoundness: number; vignetteFeather: number;
  lutIntensity: number; lutIsSceneReferred: boolean; lutName: string | null; lutPath: string | null; lutSize: number;
  lensBlurEnabled: boolean; lensBlurAmount: number; lensBlurDiffusion: number; lensBlurShape: LensBlurShape;
  lensBlurDepthMap: string | null;
  lensBlurMinDepth: number; lensBlurMaxDepth: number; lensBlurMinFade: number; lensBlurMaxFade: number;
  rotation: number; orientationSteps: number; flipHorizontal: boolean; flipVertical: boolean;
  crop: CropRect | null; aspectRatio: number | null;
  transformDistortion: number; transformVertical: number; transformHorizontal: number; transformRotate: number;
  transformAspect: number; transformScale: number; transformXOffset: number; transformYOffset: number;
  lensCorrectionMode: LensCorrectionMode; lensMaker: string | null; lensModel: string | null;
  lensDistortionAmount: number; lensVignetteAmount: number; lensTcaAmount: number;
  lensDistortionEnabled: boolean; lensTcaEnabled: boolean; lensVignetteEnabled: boolean;
  lensDistortionParams: LensDistortionParams | null;
  masks: MaskContainer[];
  sectionVisibility: SectionVisibility;
  sectionOrder: SectionId[];
}

export const DEFAULT_RECIPE: Recipe = {
  "exposure": 0.0,
  "brightness": 0.0,
  "contrast": 0.0,
  "highlights": 0.0,
  "shadows": 0.0,
  "whites": 0.0,
  "blacks": 0.0,
  "toneMapper": "basic",
  "curves": {
    "luma": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "red": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "green": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "blue": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ]
  },
  "pointCurves": {
    "luma": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "red": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "green": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ],
    "blue": [
      {
        "x": 0.0,
        "y": 0.0
      },
      {
        "x": 255.0,
        "y": 255.0
      }
    ]
  },
  "parametricCurve": {
    "luma": {
      "darks": 0.0,
      "shadows": 0.0,
      "highlights": 0.0,
      "lights": 0.0,
      "whiteLevel": 0.0,
      "blackLevel": 0.0,
      "split1": 25.0,
      "split2": 50.0,
      "split3": 75.0
    },
    "red": {
      "darks": 0.0,
      "shadows": 0.0,
      "highlights": 0.0,
      "lights": 0.0,
      "whiteLevel": 0.0,
      "blackLevel": 0.0,
      "split1": 25.0,
      "split2": 50.0,
      "split3": 75.0
    },
    "green": {
      "darks": 0.0,
      "shadows": 0.0,
      "highlights": 0.0,
      "lights": 0.0,
      "whiteLevel": 0.0,
      "blackLevel": 0.0,
      "split1": 25.0,
      "split2": 50.0,
      "split3": 75.0
    },
    "blue": {
      "darks": 0.0,
      "shadows": 0.0,
      "highlights": 0.0,
      "lights": 0.0,
      "whiteLevel": 0.0,
      "blackLevel": 0.0,
      "split1": 25.0,
      "split2": 50.0,
      "split3": 75.0
    }
  },
  "curveMode": "point",
  "temperature": 0.0,
  "tint": 0.0,
  "vibrance": 0.0,
  "saturation": 0.0,
  "hue": 0.0,
  "colorGrading": {
    "balance": 0.0,
    "blending": 50.0,
    "global": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "shadows": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "midtones": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "highlights": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    }
  },
  "hsl": {
    "reds": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "oranges": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "yellows": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "greens": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "aquas": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "blues": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "purples": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    },
    "magentas": {
      "hue": 0.0,
      "saturation": 0.0,
      "luminance": 0.0
    }
  },
  "colorCalibration": {
    "shadowsTint": 0.0,
    "redHue": 0.0,
    "redSaturation": 0.0,
    "greenHue": 0.0,
    "greenSaturation": 0.0,
    "blueHue": 0.0,
    "blueSaturation": 0.0
  },
  "clarity": 0.0,
  "structure": 0.0,
  "dehaze": 0.0,
  "centré": 0.0,
  "sharpness": 0.0,
  "sharpnessThreshold": 15.0,
  "lumaNoiseReduction": 0.0,
  "colorNoiseReduction": 0.0,
  "chromaticAberrationRedCyan": 0.0,
  "chromaticAberrationBlueYellow": 0.0,
  "glowAmount": 0.0,
  "halationAmount": 0.0,
  "flareAmount": 0.0,
  "grainAmount": 0.0,
  "grainSize": 25.0,
  "grainRoughness": 50.0,
  "vignetteAmount": 0.0,
  "vignetteMidpoint": 50.0,
  "vignetteRoundness": 0.0,
  "vignetteFeather": 50.0,
  "lutIntensity": 100.0,
  "lutIsSceneReferred": false,
  "lutName": null,
  "lutPath": null,
  "lutSize": 0,
  "lensBlurEnabled": false,
  "lensBlurAmount": 40.0,
  "lensBlurDiffusion": 0.0,
  "lensBlurShape": "circle",
  "lensBlurDepthMap": null,
  "lensBlurMinDepth": 20.0,
  "lensBlurMaxDepth": 100.0,
  "lensBlurMinFade": 20.0,
  "lensBlurMaxFade": 20.0,
  "rotation": 0.0,
  "orientationSteps": 0,
  "flipHorizontal": false,
  "flipVertical": false,
  "crop": null,
  "aspectRatio": null,
  "transformDistortion": 0.0,
  "transformVertical": 0.0,
  "transformHorizontal": 0.0,
  "transformRotate": 0.0,
  "transformAspect": 0.0,
  "transformScale": 100.0,
  "transformXOffset": 0.0,
  "transformYOffset": 0.0,
  "lensCorrectionMode": "manual",
  "lensMaker": null,
  "lensModel": null,
  "lensDistortionAmount": 100.0,
  "lensVignetteAmount": 100.0,
  "lensTcaAmount": 100.0,
  "lensDistortionEnabled": true,
  "lensTcaEnabled": true,
  "lensVignetteEnabled": true,
  "lensDistortionParams": null,
  "masks": [],
  "sectionVisibility": {
    "basic": true,
    "curves": true,
    "color": true,
    "details": true,
    "effects": true
  },
  "sectionOrder": [
    "basic",
    "curves",
    "color",
    "details",
    "effects"
  ]
};

export interface ParamRange { min: number; max: number; step: number; section: SectionId | null; }
export const RECIPE_PARAM_RANGES: Record<string, ParamRange> = {
  "blacks": {
    "max": 100.0,
    "min": -100.0,
    "section": "basic",
    "step": 1.0
  },
  "brightness": {
    "max": 5.0,
    "min": -5.0,
    "section": "basic",
    "step": 0.01
  },
  "centré": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "chromaticAberrationBlueYellow": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "chromaticAberrationRedCyan": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "clarity": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "colorNoiseReduction": {
    "max": 100.0,
    "min": 0.0,
    "section": "details",
    "step": 1.0
  },
  "contrast": {
    "max": 100.0,
    "min": -100.0,
    "section": "basic",
    "step": 1.0
  },
  "dehaze": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "exposure": {
    "max": 5.0,
    "min": -5.0,
    "section": "basic",
    "step": 0.01
  },
  "flareAmount": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "glowAmount": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "grainAmount": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "grainRoughness": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "grainSize": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "halationAmount": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "highlights": {
    "max": 100.0,
    "min": -100.0,
    "section": "basic",
    "step": 1.0
  },
  "hue": {
    "max": 180.0,
    "min": -180.0,
    "section": "color",
    "step": 1.0
  },
  "lensBlurAmount": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensBlurDiffusion": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensBlurMaxDepth": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensBlurMaxFade": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensBlurMinDepth": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensBlurMinFade": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "lensDistortionAmount": {
    "max": 200.0,
    "min": 0.0,
    "section": null,
    "step": 1.0
  },
  "lensTcaAmount": {
    "max": 200.0,
    "min": 0.0,
    "section": null,
    "step": 1.0
  },
  "lensVignetteAmount": {
    "max": 200.0,
    "min": 0.0,
    "section": null,
    "step": 1.0
  },
  "lumaNoiseReduction": {
    "max": 100.0,
    "min": 0.0,
    "section": "details",
    "step": 1.0
  },
  "lutIntensity": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "rotation": {
    "max": 180.0,
    "min": -180.0,
    "section": null,
    "step": 0.01
  },
  "saturation": {
    "max": 100.0,
    "min": -100.0,
    "section": "color",
    "step": 1.0
  },
  "shadows": {
    "max": 100.0,
    "min": -100.0,
    "section": "basic",
    "step": 1.0
  },
  "sharpness": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "sharpnessThreshold": {
    "max": 80.0,
    "min": 0.0,
    "section": "details",
    "step": 1.0
  },
  "structure": {
    "max": 100.0,
    "min": -100.0,
    "section": "details",
    "step": 1.0
  },
  "temperature": {
    "max": 100.0,
    "min": -100.0,
    "section": "color",
    "step": 1.0
  },
  "tint": {
    "max": 100.0,
    "min": -100.0,
    "section": "color",
    "step": 1.0
  },
  "transformAspect": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "transformDistortion": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "transformHorizontal": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "transformRotate": {
    "max": 45.0,
    "min": -45.0,
    "section": null,
    "step": 1.0
  },
  "transformScale": {
    "max": 150.0,
    "min": 50.0,
    "section": null,
    "step": 1.0
  },
  "transformVertical": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "transformXOffset": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "transformYOffset": {
    "max": 100.0,
    "min": -100.0,
    "section": null,
    "step": 1.0
  },
  "vibrance": {
    "max": 100.0,
    "min": -100.0,
    "section": "color",
    "step": 1.0
  },
  "vignetteAmount": {
    "max": 100.0,
    "min": -100.0,
    "section": "effects",
    "step": 1.0
  },
  "vignetteFeather": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "vignetteMidpoint": {
    "max": 100.0,
    "min": 0.0,
    "section": "effects",
    "step": 1.0
  },
  "vignetteRoundness": {
    "max": 100.0,
    "min": -100.0,
    "section": "effects",
    "step": 1.0
  },
  "whites": {
    "max": 100.0,
    "min": -100.0,
    "section": "basic",
    "step": 1.0
  }
};

/**
 * Lap legacy CSS-filter scale: 0..=200 with neutral 100.
 * Recipe deviation scale: -100..=100 with neutral 0 (RapidRAW semantics).
 * The conversion is arithmetic; field names are never matched by similarity.
 */
function clamp(value: number, min: number, max: number): number {
  if (Number.isNaN(value)) return min;
  return Math.min(max, Math.max(min, value));
}

export function saturationFromLapLegacy(legacy: number): number {
  return clamp(legacy, 0, 200) - 100;
}

export function saturationToLapLegacy(recipe: number): number {
  return clamp(recipe, -100, 100) + 100;
}

// ---------------------------------------------------------------------------
// LAP IPC CONTRACT (mirrors src-tauri/src/develop/sessions.rs serde DTOs)
// ---------------------------------------------------------------------------

/**
 * Result of `develop_open_edit_session`. `revision` is Lap's durable
 * sidecar-aligned revision (0 = unedited initial state).
 */
export interface OpenedEditSession {
  sessionId: number;
  assetId: string;
  variantId: string;
  revision: number;
  dimensions: [number, number];
  sourceFingerprint: string;
  envelope: RecipeEnvelopeValue;
}

/** The durable envelope as JSON (schema-validated by the Rust host). */
export type RecipeEnvelopeValue = RecipeEnvelope;

/** Preview quality tiers (engine session contract). */
export type PreviewQuality = 'Interactive' | 'Settled';

/**
 * A successfully rendered preview. Pixels travel only through the bounded
 * raw-byte handle transport (`develop_take_preview_frame`), never inside this
 * JSON payload (spec: bounded buffers/asset transport for previews).
 */
export interface PreviewTicket {
  sessionId: number;
  assetId: string;
  variantId: string;
  generation: number;
  quality: PreviewQuality;
  width: number;
  height: number;
  handle: string;
  byteLen: number;
}

/** Final state of one preview request. */
export type PreviewWait =
  | { status: 'completed'; ticket: PreviewTicket }
  | { status: 'cancelled' }
  | { status: 'failed'; code: string; message: string };

/** Durable commit acknowledgment (`revision = expectedRevision + 1`). */
export interface CommitReceipt {
  sessionId: number;
  revision: number;
  contentHash: string | null;
  sidecarPath: string | null;
  projectionApplied: boolean;
  projectionError: string | null;
}

/** Result of closing a session (`revision` is sidecar-aligned). */
export interface ClosedEditSession {
  sessionId: number;
  revision: number;
  releasedPreviewCacheEntries: number;
  releasedPreviewCacheBytes: number;
}

/** Offscreen GPU device status (explicit capability report; spec A7/A11). */
export interface DevelopGpuStatus {
  available: boolean;
  error: string | null;
  adapterName: string;
  backend: string;
  maxTextureDimension2d: number;
  maxBufferSize: number;
}

/** Engine identity + device capability report. */
export interface CapabilityReport {
  gpu: DevelopGpuStatus;
  engineRevision: string;
  editModelVersion: string;
  schemaVersion: number;
  previewMaxEdge: number;
}

// ---------------------------------------------------------------------------
// DURABLE DERIVATIVE EXPORT (mirrors src-tauri/src/develop/export.rs, lap-7ae)
// ---------------------------------------------------------------------------

/** Output container of the derivative. */
export type ExportFormat = 'png' | 'jpeg';

/** Receipt of a completed derivative export (`export_developed`). */
export interface ExportReceipt {
  assetId: string;
  variantId: string;
  /** The committed revision that was rendered (exactly the requested one). */
  revision: number;
  destination: string;
  format: ExportFormat;
  width: number;
  height: number;
  bytesWritten: number;
  sourceFingerprint: string;
  /** Content hash of the committed recipe that produced this derivative. */
  contentHash: string | null;
}

/** Final state of one export request. Cancellation is an outcome, not an
 * error; a cancelled export never leaves a partial file. */
export type ExportCompletion =
  | { status: 'completed'; receipt: ExportReceipt }
  | { status: 'cancelled' };
